### ISSUE TITLE
submit the 9.0.3 please

### ISSUE THREAD

**Issue by danielb2** [z0mt3c/hapi.docset#5]
I tried just adding it using https://github.com/z0mt3c/hapi.docset/raw/hapi/releases/hapi-9.0.3.tgz but that didn't seem to work.

**Comment by z0mt3c** [comment]
Yes, it requires another pull request in the Dash-User-Contributions Repo. But i just sent it on the way!

**Comment by danielb2** [comment]
Thanks ! :)
